# Generated by Django 3.2.9 on 2022-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0002_auto_20211215_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='bussinessinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('searchURL', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
