# Generated by Django 3.2.9 on 2022-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0005_alter_bussinessinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessinfo',
            name='searchURL',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
