# Generated by Django 3.2.9 on 2022-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0007_auto_20220109_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='detailcapture',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='namecapture',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='pricecapture',
        ),
        migrations.AddField(
            model_name='bussinessinfo',
            name='detailcaptureclass',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bussinessinfo',
            name='detailcapturetag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bussinessinfo',
            name='namecaptureclass',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bussinessinfo',
            name='namecapturetag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bussinessinfo',
            name='pricecaptureclass',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bussinessinfo',
            name='pricecapturetag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
