# Generated by Django 3.2.9 on 2022-01-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0008_auto_20220109_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessinfo',
            name='detailcaptureclass',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='detailcapturetag',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='namecaptureclass',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='namecapturetag',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='pricecaptureclass',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='pricecapturetag',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
