# Generated by Django 3.2.9 on 2022-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0009_auto_20220109_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessinfo',
            name='detailcaptureclass',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='detailcapturetag',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='namecaptureclass',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='namecapturetag',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='pricecaptureclass',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bussinessinfo',
            name='pricecapturetag',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
