# Generated by Django 3.2.9 on 2022-01-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0010_auto_20220109_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='detailcaptureclass',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='detailcapturetag',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='namecaptureclass',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='namecapturetag',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='pricecaptureclass',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='pricecapturetag',
        ),
        migrations.RemoveField(
            model_name='bussinessinfo',
            name='searchURL',
        ),
    ]
