# Generated by Django 3.2.9 on 2022-01-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0011_auto_20220122_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
