# Generated by Django 3.2.9 on 2022-01-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0012_pocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
