# Generated by Django 3.2.9 on 2022-01-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0013_auto_20220124_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
