# Generated by Django 3.2.9 on 2022-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanaly', '0015_auto_20220124_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
